import Head from "next/head";
import Image from "next/image";
import { Row, Col } from "antd";
import { useEffect } from "react";
import LoginForm from "../components/login/LoginForm";
export default function Home() {
  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("/api/hello");
      const json = await res.json();
      console.log("🚀 ~ file: index.js ~ line 9 ~ fetchData ~ json", json);
    };
    fetchData();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Row className="login-page-wrapper">
        <Col span={16} className="col-left" />
        <Col span={8} className="col-right">
          <div className="logo-wrapper">
            <img src="/logo.webp" />
          </div>
          <LoginForm />
        </Col>
      </Row>
    </div>
  );
}
